# Generated by Django 5.0.7 on 2024-07-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('gambar', models.ImageField(upload_to='galeri/')),
                ('tanggal_unggah', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Foto',
            },
        ),
    ]
